version: '2'
services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    working_dir: '/usr/src/app'
    command: [rails, server, -p, '3000', -b, 0.0.0.0]
    links:
      - postgres
    env_file:
      - web.env

  postgres:
    image: postgres:9.5
    ports:
      - "5435:5432"
