default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  min_messages: warning
  timeout: 5000
  username: postgres
  host: postgres
  port: 5432

development:
  <<: *default
  database: 'rusty_shop_development'
